---
abstract: 'Accessors whose values come from a factory'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Class::Factory::Enhanced: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100960'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Accessor-FactoryTyped
provides:
  Class::Accessor::FactoryTyped:
    file: lib/Class/Accessor/FactoryTyped.pm
    version: 1.100970
recommends: {}
requires:
  Carp: 0
  Class::Accessor::Complex: 0
  Class::Accessor::Installer: 0
  Data::Miscellany: 0
  UNIVERSAL::require: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Class-Accessor-FactoryTyped
  homepage: http://search.cpan.org/dist/Class-Accessor-FactoryTyped/
  repository: origin
version: 1.100970
