--- 
abstract: accessors whose values come from a factory
author: 
  - "{% ELSE %}"
build_requires: 
  Test::Compile: 0
  Test::More: 0
  UNIVERSAL::require: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Class-Accessor-FactoryTyped
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor: 0
  Class::Accessor::Installer: 0
  Class::Factory::Enhanced: 0
  Data::Miscellany: 0
  UNIVERSAL::require: 0
  perl: 5.6.0
version: 0.03
