---
abstract: 'Accessors whose values come from a factory'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Accessor-FactoryTyped
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor: 0
  Class::Accessor::Installer: 0
  Class::Factory::Enhanced: 0
  Data::Miscellany: 0
  UNIVERSAL::require: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Class-Accessor-FactoryTyped
  homepage: http://search.cpan.org/dist/Class-Accessor-FactoryTyped/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/class-accessor-factorytyped.git
version: 0.04
